spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  mvc:
    dispatch-options-request: true

app:
  route:
    path: /com/tieto/mikactom/reactworkshop

logging:
  level:
    org:
      hibernate:
        type: trace